import * as constructs from 'constructs';
import { SchedulerType, ClusterSize } from './enums';
import { CfnCluster } from './pcs.generated';
import { ClusterSlurmConfigurationProps, SlurmConfiguration } from './slurm-configuration';
import * as ec2 from '../../aws-ec2';
import * as cdk from '../../core';

/**
 * Error thrown when an invalid cluster ARN is provided
 */
class InvalidClusterArnError extends Error {
  constructor(arn: string) {
    super(`Invalid cluster ARN: ${arn}`);
    this.name = 'InvalidClusterArnError';
  }
}

/**
 * Scheduler configuration for a cluster
 */
export interface SchedulerConfiguration {
  /**
   * The scheduler type
   */
  readonly type: SchedulerType;

  /**
   * The scheduler version
   */
  readonly version: string;
}

/**
 * Properties for defining a PCS Cluster
 */
export interface ClusterProps {
  /**
   * The name that identifies the cluster
   * @default - will be autogenerated
   */
  readonly clusterName?: string;

  /**
   * The subnet IDs where the cluster control plane will be deployed.
   * AWS PCS currently supports only 1 subnet in this list.
   */
  readonly subnetIds: string[];

  /**
   * Security groups for the cluster control plane
   */
  readonly securityGroups: ec2.ISecurityGroup[];

  /**
   * The size of the cluster
   */
  readonly size: ClusterSize;

  /**
   * The scheduler type and version
   */
  readonly scheduler: SchedulerConfiguration;

  /**
   * Slurm-specific configuration options
   * @default - No Slurm configuration
   */
  readonly slurmConfiguration?: ClusterSlurmConfigurationProps;

  /**
   * Tags to apply to the cluster
   * @default - No tags
   */
  readonly tags?: Record<string, string>;
}

/**
 * Represents a PCS Cluster
 */
export interface ICluster extends cdk.IResource {
  /**
   * The ARN of the cluster
   * @attribute
   */
  readonly clusterArn: string;

  /**
   * The ID of the cluster
   * @attribute
   */
  readonly clusterId: string;

  /**
   * The name of the cluster
   * @attribute
   */
  readonly clusterName: string;
}

/**
 * Properties for importing an existing cluster
 */
export interface ClusterAttributes {
  /**
   * The ARN of the cluster
   */
  readonly clusterArn: string;

  /**
   * The ID of the cluster
   */
  readonly clusterId: string;

  /**
   * The name of the cluster
   */
  readonly clusterName: string;
}

/**
 * A PCS Cluster for high-performance computing workloads
 */
export class Cluster extends cdk.Resource implements ICluster {
  /**
   * Import an existing cluster by specifying its attributes
   */
  public static fromClusterAttributes(scope: constructs.Construct, id: string, attrs: ClusterAttributes): ICluster {
    class Import extends cdk.Resource implements ICluster {
      public readonly clusterArn = attrs.clusterArn;
      public readonly clusterId = attrs.clusterId;
      public readonly clusterName = attrs.clusterName;
    }

    return new Import(scope, id);
  }

  /**
   * Import an existing cluster by its ARN
   */
  public static fromClusterArn(scope: constructs.Construct, id: string, clusterArn: string): ICluster {
    const arnParts = cdk.Arn.split(clusterArn, cdk.ArnFormat.SLASH_RESOURCE_NAME);
    const clusterId = arnParts.resourceName;

    if (!clusterId) {
      throw new InvalidClusterArnError(clusterArn);
    }

    class Import extends cdk.Resource implements ICluster {
      public readonly clusterArn = clusterArn;
      public readonly clusterId = clusterId!;
      public readonly clusterName = clusterId!; // Best guess since we only have the ARN
    }

    return new Import(scope, id);
  }

  /**
   * Import an existing cluster by its ID
   */
  public static fromClusterId(scope: constructs.Construct, id: string, clusterId: string): ICluster {
    const stack = cdk.Stack.of(scope);
    const clusterArn = cdk.Arn.format({
      service: 'pcs',
      resource: 'cluster',
      resourceName: clusterId,
    }, stack);

    return Cluster.fromClusterArn(scope, id, clusterArn);
  }

  public readonly clusterArn: string;
  public readonly clusterId: string;
  public readonly clusterName: string;

  private readonly cfnCluster: CfnCluster;

  constructor(scope: constructs.Construct, id: string, props: ClusterProps) {
    super(scope, id);

    // Set up scheduler configuration
    const scheduler = props.scheduler;

    // Configure Slurm settings
    let slurmConfiguration;
    if (props.slurmConfiguration) {
      slurmConfiguration = SlurmConfiguration.forCluster(props.slurmConfiguration);
    }

    // Create the cluster
    this.cfnCluster = new CfnCluster(this, 'Resource', {
      name: props.clusterName,
      size: props.size,
      networking: {
        subnetIds: props.subnetIds,
        securityGroupIds: props.securityGroups.map(sg => sg.securityGroupId),
      },
      scheduler: {
        type: scheduler.type,
        version: scheduler.version,
      },
      slurmConfiguration,
      tags: props.tags,
    });

    this.clusterArn = this.cfnCluster.attrArn;
    this.clusterId = this.cfnCluster.attrId;
    this.clusterName = this.cfnCluster.name || this.cfnCluster.attrId;
  }

  /**
   * Add tags to the cluster
   */
  public addTags(tags: Record<string, string>): void {
    Object.entries(tags).forEach(([key, value]) => {
      cdk.Tags.of(this).add(key, value);
    });
  }

  /**
   * Get the endpoints for connecting to the cluster scheduler
   */
  public get endpoints(): cdk.IResolvable {
    return this.cfnCluster.attrEndpoints;
  }

  /**
   * Get the status of the cluster
   */
  public get status(): string {
    return this.cfnCluster.attrStatus;
  }

  /**
   * Get error information if the cluster failed to provision
   */
  public get errorInfo(): cdk.IResolvable {
    return this.cfnCluster.attrErrorInfo;
  }
}
